### ISSUE TITLE
Add support for ultrawide resolutions

### ISSUE THREAD

**Issue by mahmoudhossam** [zero334/Dawn-of-War-Widescreen-Fix#4]
I have a monitor with a 21:9 aspect ratio and a resolution of 3440 * 1440.

I tried running the fix and got the following exception because my aspect ratio is not supported:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Dawn_of_War_Widescreen_Fix.AttributeStorage.CheckAspectRatioValues()
   at Dawn_of_War_Widescreen_Fix.Form.BtnStart_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Dawn of War Widescreen Fix
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Mahmoud/Downloads/Dawn.of.War.Widescreen.Fix.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9206.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
```

**Comment by purplekairi1312** [comment]
+1 to this

**Comment by zero334** [comment]
Should be fixed with commit 3c798c5d9203acce249f865df088b27b5b8c549e.

**Comment by mahmoudhossam** [comment]
@zero334 I pulled the latest code and built it and I'm having this exact problem https://github.com/zero334/Dawn-of-War-Widescreen-Fix/issues/5#issuecomment-2399667493

I don't have multiple screens though, only the 1920*1080 option works but that's not ultrawide.

Would it make sense to add ultrawide options to the UI choices?

**Comment by zero334** [comment]
@mahmoudhossam , o.k. but you did not get the System.NullReferenceException, right? Could it be, that your dpi setting in windows is not set to 100%?
I will prepare a solution for you to test on a separate branch asap.

I think it actually makes the most sense to detect the resolution of all connected screens and then let the user choose which resolution will be patched. With the last commits we are not bound to fixed choices anymore, since I'm now calculating the required string. If we don't get the solution working and PrimaryScreen.Size keeps returning the wrong data, I will add an override.

**Comment by mahmoudhossam** [comment]
@zero334 I use windows with 125% scaling if that helps.

I don't get the System.NullReferenceException anymore, but the application hangs after it fires the notification that the game was patched successfully, I can only close the window but not click on "Done" for example.

**Comment by zero334** [comment]
@mahmoudhossam Please give it a try with the changes on branch [native-resolution-detection](https://github.com/zero334/Dawn-of-War-Widescreen-Fix/tree/native-resolution-detection).

**Comment by mahmoudhossam** [comment]
@zero334 That branch seems to set the game to 1600 by 1200, but not any wider.

Can we reopen this issue please?

**Comment by zero334** [comment]
What was recognised as resolution on your system? Were you able to override it?

**Comment by mahmoudhossam** [comment]
I could override it but it was detecting the correct resolution for me so I didn't have to.

It ran without issues, but the game had black bars on both sides.
